name: interview
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cupertino_icons: ^0.1.3
  # state management
  get: 4.6.1
  # with no version will get the latest one, but it's not good for detecting crashes for future versions
  flutter_svg:

  #loading animation
  shimmer: ^2.0.0

  # value equality
  equatable: ^2.0.3

  # Offline Management
  hive:
  hive_flutter:

  # concept class attribute inside class
  freezed_annotation:

  uuid:

  # image picker (camera,photos..)
  image_picker:

  path_provider:

  # unit testing
  mockito:

  # dependency injection
  get_it:
  injectable:

  # Responsive Text
  auto_size_text: ^3.0.0

  # Either left or right result
  #dartz:
  dartz: ^0.10.1


  flutter:
    sdk: flutter

dev_dependencies:
  # flutter pub run build_runner watch --delete-conflicting-outputs
  build_runner:

  # principle to generate class inside class as attribute
  freezed:

  # generate support of saving a model as json locally
  hive_generator:

  # for unit testing
  http_mock_adapter:

  # generate dependency injection
  injectable_generator:
  lints: 1.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/fonts/Product-Sans-Regular.ttf
          weight: 500
        - asset: assets/fonts/Product-Sans-Bold.ttf
          weight: 700

